# Generated by Django 3.2.4 on 2021-07-10 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('klass', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='SubmissionStatus',
        ),
    ]
