# Generated by Django 3.2.4 on 2021-06-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='joining_code_expiry_date',
            field=models.DateField(),
        ),
    ]
