# Generated by Django 3.2.4 on 2021-07-24 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('total_marks', models.IntegerField()),
                ('marks_released', models.BooleanField(default=False)),
                ('due_on', models.DateTimeField()),
                ('ques_file', models.FileField(blank=True, null=True, upload_to='questions_file_folder/')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_class_id', to='klass.classes')),
            ],
        ),
    ]
