# Generated by Django 3.2.4 on 2021-07-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('klass', '0001_initial'),
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_status', models.BooleanField(default=False)),
                ('marks_scored', models.IntegerField(default=0)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submission_status', to='assignment.assignment')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_status_class_id', to='klass.classes')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_status_student_id', to='authentication.student')),
            ],
        ),
    ]
