# Generated by Django 3.2.4 on 2021-07-24 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('assignment', '0002_submissionstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_file', models.FileField(upload_to='submissions/')),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_assignment_id', to='assignment.assignment')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_response_student_id', to='authentication.student')),
            ],
        ),
    ]
