# Generated by Django 3.2.4 on 2021-07-26 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_assignment_response_idgraded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment_response',
            old_name='idGraded',
            new_name='isGraded',
        ),
        migrations.RenameField(
            model_name='assignment_response',
            old_name='submited_data',
            new_name='submited_date',
        ),
    ]
